Adding draft project proposal of: Ventilator Knowledge Database
Helpful-Engineers/resources pull request #36
Opened 2020-03-16 02:09 UTC by VictorMirandaEE

2020-03-16 02:15 UTC, VictorMirandaEE commented
Project draft is here: https://github.com/VictorMirandaEE/resources/blob/PROJECT-ventilator_knowledge_database/software/proposals/ventilator_knowledge_database.md

2020-03-16 02:50 UTC, 2001kraft commented on software/proposals/ventilator_knowledge_database.md
> +One major concern is the availability of proper patient care equipment in the worst-case scenario of the COVID-19 outbreak, especially in the countries with low Universal Health Coverage (UHC) index
```suggestion
One major concern is the availability of proper patient care equipment in the worst-case scenario of the COVID-19 outbreak, especially in the countries with low Universal Health Coverage (UHC) index (https://www.who.int/news-room/fact-sheets/detail/universal-health-coverage-(uhc)).
```
Please outline these in "Known Issues"

2020-03-16 02:50 UTC, 2001kraft commented on software/proposals/ventilator_knowledge_database.md
> +## 💻Implementation Suggestion
Please fill out this category

2020-03-16 02:51 UTC, 2001kraft requested changes
Please finish filling out the template. Otherwise, we will not be able to adequately assess your proposal.

2020-03-16 02:51 UTC, 2001kraft commented on software/proposals/ventilator_knowledge_database.md
> +## 💪 Impact of Potential Solution
Please state impact

2020-03-16 02:51 UTC, 2001kraft commented on software/proposals/ventilator_knowledge_database.md
> +## 🙌 Criteria for Success
Please outline the KPIs

2020-03-17 03:45 UTC, 2001kraft approved these changes

2020-03-17 03:46 UTC, VictorMirandaEE commented
Review done. I did my best due to the timing constraints.

2020-03-17 03:46 UTC, merged