added fake_news_tracker app proposal
Helpful-Engineers/resources pull request #37
Opened 2020-03-16 02:41 UTC by jmartinhoj

Added a proposal of an app to track fake news about the new coronavirus!

2020-03-16 02:53 UTC, 2001kraft requested changes
Please fill out the template completely.

2020-03-16 02:53 UTC, 2001kraft commented on software/proposals/fake_news_tracker.md
> +## 💪 Impact of Potential Solution
Please state the impact

2020-03-16 02:53 UTC, 2001kraft commented on software/proposals/fake_news_tracker.md
> +## 🙌 Criteria for Success
Please state KPIs

2020-03-16 02:53 UTC, 2001kraft commented on software/proposals/fake_news_tracker.md
> +## 😅 Known Issues
What are the known issues with this project?

2020-03-16 02:53 UTC, 2001kraft commented on software/proposals/fake_news_tracker.md
> +## 💻Implementation Suggestion
Please fill out the implementation—this is crucial for mobile products

2020-04-02 09:32 UTC, mazaira commented
Closing by lack of feedback. Please feel free to re-open if there would be any changes from the current state.

2020-04-02 09:32 UTC, closed without merging